// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_render.ts";
import * as $2 from "./routes/api/[...path].ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/tutorials/[...path].tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_render.ts": $1,
    "./routes/api/[...path].ts": $2,
    "./routes/index.tsx": $3,
    "./routes/tutorials/[...path].tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
