name: Check
on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.23.0"

      - name: Lint
        run: deno lint

  fmt:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.23.0"

      - name: Format
        run: deno fmt --check
